server {
    listen 80;
    server_name _;
    
    # ❌ root /var/www/html/public;
    # ✅ Laravel ရဲ့ public folder တည်နေရာကို Docker WORKDIR နှင့် ကိုက်ညီအောင်ထားပါ
    root /var/www/html/public; 

    # index ကို index.php ကို အရှေ့ဆုံးက ထားပါ
    index index.php index.html index.htm;
    charset utf-8;

    # Backend API requests များကို Laravel Backend (index.php) ဆီ ပို့ရန်
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # SPA Routes များကို index.php ဆီ ပို့ရန်
    # ✅ try_files $uri $uri/ /index.php?$query_string; သို့မဟုတ် /index.html;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Laravel optimized 404 handling
    error_page 404 /index.php;

    # PHP-FPM Handler
    location ~ \.php$ {
        # dockerfile က alpine သုံးထားလို့ socket အစား port သုံးတာ ပိုစိတ်ချရပါတယ်
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}