[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm83 -F ; မိမိ PHP Version အလိုက် ပြောင်းပါ (dockerfile ထဲက php:8.4 ဆိုရင် php-fpm84 ဖြစ်နိုင်ပါတယ်)
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:nginx]
command=nginx -g "daemon off;" ; ❌ daemon mode on ဖြစ်နေရင် supervisor က process ကို drop လုပ်ပစ်ပြီး 404 ပြပါလိမ့်မယ်
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log